version: '2'

networks:
  %(database_name)s:

services:
  database:
    image: %(database_name)s
    environment:
      PG_LOG_MIN_MESSAGES: 'info'
      PG_LOG_MIN_DURATION_STATEMENT: '0'
    cpuset: 0,1
    mem_limit: 512M
    networks:
      - %(database_name)s
    ports:
      - '20000:5432'
